version: '3.5'

services:
  db:
    image: mysql:latest
    container_name: ktor-note-example-db

    ports:
      - 3307:3306

    environment:
      MYSQL_DATABASE: ktor_note
      MYSQL_ROOT_PASSWORD: toor

    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
    driver: local
